// src/validator.ts

import { isValidLicenseFormat, isValidDeviceHash } from './crypto';
import { 
  ActivateRequest, 
  VerifyRequest, 
  AdminGenerateRequest, 
  AdminResetRequest, 
  AdminRevokeRequest 
} from './types';

export class ValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ValidationError';
  }
}

// ==========================================
// HELPER FUNCTIONS
// ==========================================

function isString(val: unknown): val is string {
  return typeof val === 'string';
}

function isNumber(val: unknown): val is number {
  return typeof val === 'number' && Number.isFinite(val) && Number.isInteger(val);
}

function isValidAppVersion(version: string): boolean {
  // Enforces strict SemVer format: X.Y.Z (e.g., 1.0.0, 12.34.56)
  return /^\d+\.\d+\.\d+$/.test(version);
}

function checkUnexpectedFields(body: Record<string, any>, allowedKeys: string[]) {
  for (const key of Object.keys(body)) {
    if (!allowedKeys.includes(key)) {
      throw new ValidationError(`Unexpected field: ${key}`);
    }
  }
}

// ==========================================
// PUBLIC ENDPOINT VALIDATORS
// ==========================================

export function validateActivateRequest(body: any): ActivateRequest {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    throw new ValidationError('Request body must be a JSON object');
  }

  const { license, deviceHash, appVersion } = body;

  if (!isString(license) || !isValidLicenseFormat(license)) {
    throw new ValidationError('Invalid license format');
  }
  if (!isString(deviceHash) || !isValidDeviceHash(deviceHash)) {
    throw new ValidationError('Invalid device hash format');
  }
  if (!isString(appVersion) || !isValidAppVersion(appVersion)) {
    throw new ValidationError('Invalid app version format');
  }

  checkUnexpectedFields(body, ['license', 'deviceHash', 'appVersion']);

  return { license, deviceHash, appVersion };
}

export function validateVerifyRequest(body: any): VerifyRequest {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    throw new ValidationError('Request body must be a JSON object');
  }

  const { token, deviceHash } = body;

  // Token is a JSON string generated by the server. We just check it's a non-empty string.
  if (!isString(token) || token.length < 50 || token.length > 2000) {
    throw new ValidationError('Invalid token format');
  }
  if (!isString(deviceHash) || !isValidDeviceHash(deviceHash)) {
    throw new ValidationError('Invalid device hash format');
  }

  checkUnexpectedFields(body, ['token', 'deviceHash']);

  return { token, deviceHash };
}

// ==========================================
// ADMIN ENDPOINT VALIDATORS
// ==========================================

export function validateAdminGenerateRequest(body: any): AdminGenerateRequest {
  if (!body || typeof body !== 'object') throw new ValidationError('Invalid request body');
  
  const { count, plan, batchName } = body;

  if (!isNumber(count) || count <= 0 || count > 1000) {
    throw new ValidationError('Count must be an integer between 1 and 1000');
  }
  if (!isString(plan) || plan.trim().length === 0 || plan.length > 50) {
    throw new ValidationError('Invalid plan name');
  }
  if (!isString(batchName) || batchName.trim().length === 0 || batchName.length > 100) {
    throw new ValidationError('Invalid batch name');
  }

  checkUnexpectedFields(body, ['count', 'plan', 'batchName']);

  return { count, plan, batchName };
}

export function validateAdminResetRequest(body: any): AdminResetRequest {
  if (!body || typeof body !== 'object') throw new ValidationError('Invalid request body');
  
  const { license } = body;

  if (!isString(license) || !isValidLicenseFormat(license)) {
    throw new ValidationError('Invalid license format');
  }

  checkUnexpectedFields(body, ['license']);

  return { license };
}

export function validateAdminRevokeRequest(body: any): AdminRevokeRequest {
  if (!body || typeof body !== 'object') throw new ValidationError('Invalid request body');
  
  const { license, reason } = body;

  if (!isString(license) || !isValidLicenseFormat(license)) {
    throw new ValidationError('Invalid license format');
  }
  if (!isString(reason) || reason.trim().length === 0 || reason.length > 100) {
    throw new ValidationError('Invalid revocation reason');
  }

  checkUnexpectedFields(body, ['license', 'reason']);

  return { license, reason };
}